#!/bin/sh /etc/rc.common
# Copyright (C) 2026 LuCI FanControl
# SPDX-License-Identifier: GPL-2.0-or-later

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/openwrt-fancontrol

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger fancontrol
}

reload_service() {
	stop
	start
}
