#!/bin/sh
# Resolve the latest openwrt-fancontrol release for an OpenWrt target ARCH.
# Downloads hashes.mk from the release and writes a generated Makefile fragment.
#
# Usage: resolve-fancontrol-release.sh <openwrt_arch> <github_repo> <cache_dir>
# Example: resolve-fancontrol-release.sh aarch64_cortex-a53 shizzz/openwrt-fancontrol /path/to/dl

set -e

OWRT_ARCH="$1"
REPO="$2"
CACHE_DIR="$3"

if [ -z "$OWRT_ARCH" ] || [ -z "$REPO" ] || [ -z "$CACHE_DIR" ]; then
	echo "Usage: $0 <openwrt_arch> <github_repo> <cache_dir>" >&2
	exit 1
fi

fetch() {
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$1"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO- "$1"
	else
		echo "Neither curl nor wget available" >&2
		exit 1
	fi
}

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"

VERSION="$(sh "$SCRIPT_DIR/latest-fancontrol-release.sh" "$REPO")"

if [ -z "$VERSION" ]; then
	echo "Unable to determine latest ${REPO} release tag" >&2
	exit 1
fi

ASSET_ARCH="$(sh "$SCRIPT_DIR/select-fancontrol-arch.sh" "$OWRT_ARCH" "v${VERSION}")"
if [ -z "$ASSET_ARCH" ]; then
	echo "Unable to resolve fancontrol asset for ARCH=${OWRT_ARCH} version=v${VERSION}" >&2
	exit 1
fi

mkdir -p "$CACHE_DIR"
HASHES_FILE="$CACHE_DIR/openwrt-fancontrol-hashes-v${VERSION}.mk"
HASHES_URL="https://github.com/${REPO}/releases/download/v${VERSION}/hashes.mk"

if [ ! -f "$HASHES_FILE" ]; then
	fetch "$HASHES_URL" > "$HASHES_FILE.tmp" || {
		rm -f "$HASHES_FILE.tmp"
		echo "Unable to download ${HASHES_URL}" >&2
		exit 1
	}
	mv "$HASHES_FILE.tmp" "$HASHES_FILE"
fi

HASH="$(sed -n "s/^PKG_HASH_linux-${ASSET_ARCH}:=//p" "$HASHES_FILE" | head -n1 | tr -d '[:space:]')"
if [ -z "$HASH" ]; then
	echo "No PKG_HASH_linux-${ASSET_ARCH} in hashes.mk for v${VERSION}" >&2
	exit 1
fi

OUT_FILE="$CACHE_DIR/fancontrol-release-${OWRT_ARCH}-v${VERSION}.mk"

cat > "$OUT_FILE" <<EOF
# Auto-generated by resolve-fancontrol-release.sh
FANCONTROL_VERSION:=${VERSION}
FANCONTROL_ASSET_ARCH:=${ASSET_ARCH}
FANCONTROL_ASSET:=openwrt-fancontrol-linux-${ASSET_ARCH}.tar.gz
FANCONTROL_HASH:=${HASH}
FANCONTROL_URL:=https://github.com/${REPO}/releases/download/v${VERSION}
EOF

printf '%s\n' "$OUT_FILE"
